### ISSUE TITLE
How to ignore certain files?

### ISSUE THREAD

**Issue by gianpaj** [deepscan/vscode-deepscan#28]
I tried adding this:
```json
{
  "deepscan.ignorePatterns": ["**/*.scss.d.ts"]
}
```

But Deepscan is still validating this file:
![image](https://user-images.githubusercontent.com/899175/96596500-b137ce00-12e4-11eb-8c51-48d492ebd8ea.png)

Path:
`client/src/routes/tracking/tracking.scss.d.ts`

**Comment by cimfalab** [comment]
You can not ignore certain files because the option `deepscan.ignorePatterns` is not supported in [the default mode](https://github.com/deepscan/vscode-deepscan/blob/master/README.md#settings-options). It works only in the Embedded mode of our Enterprise package. Did you find the option [here](https://deepscan.io/docs/enterprise/tools/vscode-extension/#embedded) or `package.json`? :)

While the default mode analyzes only one file at a time, the Embedded mode can inspect the whole project at once so the excluding option is provided.
But might be good if we support the option also to the default mode. The opened file matches with the ignoring patterns then it is not sent to the server, as such. Will consider as a backlog in the long roadmap.

Thank you for the issue.

**Comment by cimfalab** [comment]
@gianpaj
I just published a new 1.11.0 version which supports `ignorePatterns` option also in the default mode. Simply keep your setting and update the extension.

**Comment by gianpaj** [comment]
awesome that was super fast! thanks @cimfalab
