### ISSUE TITLE
Enable Embedded Mode

### ISSUE THREAD

**Issue by erickbrenesLT** [deepscan/vscode-deepscan#6]
Maybe I am being really thick here... how do you enable embedded mode.  Trying to scan my local project all at once vs. only on open/save of a single file.

**Comment by cimfalab** [comment]
Dear @erickbrenesLT.

Embedded mode works with the local Java language server instead of DeepScan server (https://deepscan.io).
So it can inspect the whole project in the local.
But, unfortunately, I'm afraid to say the language server can be downloaded and activated only for paid users.

I admit that README for embedded mode is insufficient and will make up the documentation now.
If you're interested in the embedded mode, please mail to support@deepscan.io.

Sorry for confusion and not helping you directly.
Thank you.

**Comment by cimfalab** [comment]
Document for the Embedded mode is [here](https://deepscan.io/docs/enterprise/tools/vscode-extension/#embedded).
